package com.smartshaped.chameleon.ml.blackBox;

import com.smartshaped.chameleon.common.exception.ConfigurationException;
import com.smartshaped.chameleon.ml.blackBox.exception.BlackBoxException;
import com.smartshaped.chameleon.ml.utils.MLConfigurationUtils;
import lombok.Getter;
import org.apache.hadoop.conf.Configuration;
import org.apache.hadoop.fs.FileSystem;
import org.apache.hadoop.fs.Path;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.apache.spark.sql.Dataset;
import org.apache.spark.sql.Row;
import org.apache.spark.sql.SparkSession;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.List;

/**
 * Java abstract class representing a black box for machine learning.
 */
public abstract class BlackBox {

    private static final Logger logger = LogManager.getLogger(BlackBox.class);

    protected MLConfigurationUtils mlConfigurationUtils;

    protected final String inputPaths;
    protected final String outputPath;
    protected final String modelPath;

    @Getter
    private Dataset<Row> predictions;

    protected BlackBox() throws ConfigurationException {

        this.mlConfigurationUtils = MLConfigurationUtils.getMlConf();

        this.inputPaths = mlConfigurationUtils.getBlackBoxInputPaths();
        this.outputPath = mlConfigurationUtils.getBlackBoxOutputPath();
        this.modelPath = mlConfigurationUtils.getBlackBoxModelPath();
    }

    /**
     * Starts the black box machine learning process.
     * <p>
     * This method performs the following steps:
     * <ul>
     * <li>Validates the parameters of this BlackBox.</li>
     * <li>Writes the input datasets to HDFS (as parquet).</li>
     * <li>Executes the pre-processing step (if any).</li>
     * <li>Runs the machine learning script.</li>
     * <li>Reads the predictions generated by the script from HDFS.</li>
     * <li>Cleans the black box folder.</li>
     * </ul>
     *
     * @param spark     the Spark session to use for reading and writing data to HDFS.
     * @param datasets  the list of input datasets to be written to HDFS.
     * @throws BlackBoxException if an error occurs during the black box process.
     */
    public void start(SparkSession spark, List<Dataset<Row>> datasets) throws BlackBoxException {

        validateParams();
        logger.info("Configurations validated");

        writeInputs(datasets);

        extraPreparation();
        runML();
        postRunning();

        // read predictions generated by python scripts
        this.predictions = spark.read().parquet(outputPath);

        cleanBlackBoxFolder();
    }

    /**
     * Cleans the black box folder by deleting the input and output folders.
     * <p>
     * This method can be overridden by subclasses to implement any additional
     * cleanup logic.
     *
     * @throws BlackBoxException if any error occurs during the deletion process
     */
    protected void cleanBlackBoxFolder() throws BlackBoxException {
        for (String inputPath : inputPaths.split(",")) {
            deleteHdfsFolder(inputPath);
        }
        deleteHdfsFolder(outputPath);
    }

    /**
     * Deletes the specified folder from the filesystem.
     * <p>
     * This method attempts to delete the folder located at the given path.
     * If the folder exists, it is deleted, and a success message is logged.
     * If the folder does not exist or deletion fails, an appropriate message is logged.
     * <p>
     *
     * @param folderPath the path of the folder to be deleted
     * @throws BlackBoxException if an error occurs during the deletion process
     */
    protected void deleteHdfsFolder(String folderPath) throws BlackBoxException {

        Configuration configuration = new Configuration();

        try {
            FileSystem fileSystem = FileSystem.get(configuration);
            Path path = new Path(folderPath);

            if (fileSystem.exists(path)) {

                boolean deleted = fileSystem.delete(path, true);
                if (deleted) {
                    logger.info("Folder deleted successfully: {}", folderPath);
                } else {
                    logger.info("Failed to delete folder: {}", folderPath);
                }
            } else {
                logger.info("Folder does not exist: {}", folderPath);
            }

            fileSystem.close();
        } catch (IOException e) {
            throw new BlackBoxException("Error deleting folder " + folderPath, e);
        }
    }

    /**
     * Runs the given command and logs its output and exit code.
     * <p>
     * This method starts the given command and logs its output line by line.
     * After the command has finished running, it logs the exit code of the
     * command. If the command exited with a non-zero exit code, this method
     * throws a {@link BlackBoxException}.
     *
     * @param processBuilder the process builder containing the command to run
     * @throws BlackBoxException if the command exited with a non-zero exit code
     */
    protected void runCommand(ProcessBuilder processBuilder) throws BlackBoxException {
        try {
            logger.info("Running command {}", processBuilder.command());
            Process process = processBuilder.start();

            BufferedReader reader = new BufferedReader(new InputStreamReader(process.getInputStream()));
            String line;
            while ((line = reader.readLine()) != null) {
                logger.info(line);
            }

            int exitCode = process.waitFor();
            if (exitCode != 0) {
                throw new BlackBoxException("Error running command, exit code: " + exitCode);
            } else {
                logger.info("Command completed successfully");
            }

        } catch (IOException e) {
            throw new BlackBoxException("Error running command", e);
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            throw new BlackBoxException("Error running command", e);
        }
    }

    /**
     * Writes the given datasets to the paths specified in the configuration file.
     * <p>
     * This method splits the input paths string into an array of paths and
     * checks if the number of paths matches the number of datasets. If not,
     * it throws an exception. Then, it writes each dataset to the
     * corresponding input path as a Parquet file.
     *
     * @param datasets the list of datasets to be written
     * @throws BlackBoxException if the number of input paths does not match
     *                           the number of datasets
     */
    private void writeInputs(List<Dataset<Row>> datasets) throws BlackBoxException {

        String[] inputPathsSplit = this.inputPaths.split(",");
        datasets = mergeDatasetsIfNecessary(datasets);
        // check if the number of input paths matches the number of datasets
        if (inputPathsSplit.length != datasets.size()) {
            throw new BlackBoxException("Number of input paths does not match number of datasets");
        }
        for (int i = 0; i < inputPathsSplit.length; i++) {
            datasets.get(i).write().mode("overwrite").parquet(inputPathsSplit[i]);
        }
    }

    /**
     * Validates the minimal parameters required for the black box process.
     * <p>
     * This method checks if the input paths, output path, and model path
     * are not empty. If any of these paths are empty, a {@link BlackBoxException}
     * is thrown with the appropriate error message.
     *
     * @throws BlackBoxException if any of the required paths are empty
     */
    protected void validateParams() throws BlackBoxException {

        if (inputPaths.trim().isEmpty()) {
            throw new BlackBoxException("The input paths are empty");
        }
        if (outputPath.trim().isEmpty()) {
            throw new BlackBoxException("The output path is empty");
        }
        if (modelPath.trim().isEmpty()) {
            throw new BlackBoxException("The model path is empty");
        }
    }

    /**
     * Runs the black box machine learning process.
     * <p>
     * This method must be implemented by the subclasses and should perform
     * the actual machine learning process using the provided input paths,
     * output path, and model path.
     *
     * @throws BlackBoxException if any error occurs during the black box process
     */
    protected abstract void runML() throws BlackBoxException;

    /**
     * Performs any necessary preparation before executing the machine learning script.
     * <p>
     * This method is intended to be overridden by subclasses to implement any
     * additional setup or preparation required before the ML script is run. This
     * could include operations such as installing python libraries.
     */
    protected abstract void extraPreparation() throws BlackBoxException;

    /**
     * Merges the datasets if necessary.
     * <p>
     * It is intended to be implemented
     * in the subclasses of this class.
     * <p>
     * The method should take the list of datasets as input and return a new
     * list of datasets that will be written to the input paths for the black box.
     * The aim is to make sure that the number of datasets to write is equal to the
     * number of input paths in the configuration.
     * <p>
     * The default implementation of this method in this class is to return
     * the input list of datasets as is.
     *
     * @param datasets the list of datasets
     * @return the merged list of datasets
     * @throws BlackBoxException if any error occurs during the merging
     */
    protected abstract List<Dataset<Row>> mergeDatasetsIfNecessary(List<Dataset<Row>> datasets) throws BlackBoxException;

    /**
     * Post-processing step after the machine learning script has finished running.
     * <p>
     * Subclasses can override this method to perform any additional post-processing
     * steps.
     */
    protected abstract void postRunning();
}
